package diagnostic

import "slices"

const CatalogVersion = "ramen.diagnostics.v1"

type Catalog struct {
	Version string  `json:"version"`
	Entries []Entry `json:"entries"`
}

type Entry struct {
	Code        string `json:"code"`
	Severity    string `json:"severity"`
	Meaning     string `json:"meaning"`
	LikelyCause string `json:"likely_cause"`
	Repair      string `json:"repair"`
}

func CatalogV1() Catalog {
	entries := []Entry{
		{Code: "ansible.always_unsupported", Severity: "error", Meaning: "A block always (finally) section cannot be lowered.", LikelyCause: "UWS core has no guaranteed-cleanup construct.", Repair: "Restructure the playbook or handle cleanup in the trusted runtime."},
		{Code: "ansible.argspec_violation", Severity: "error", Meaning: "Module arguments violate the collection argspec.", LikelyCause: "An unknown parameter, missing required parameter, or out-of-choices literal.", Repair: "Fix the task arguments or update the argspec document."},
		{Code: "ansible.delegate_unsupported", Severity: "error", Meaning: "A directive changes the execution target and cannot be lowered.", LikelyCause: "delegate_to or run_once is set on the task.", Repair: "Restructure the play so the task runs on its own target."},
		{Code: "ansible.directive_todo", Severity: "warning", Meaning: "A task directive was recorded for review and not lowered.", LikelyCause: "until/retries, changed_when, failed_when, or a runtime-owned directive is present.", Repair: "Review the generated workflow and add equivalent UWS retry/criteria handling where needed."},
		{Code: "ansible.dynamic_include", Severity: "error", Meaning: "An include construct cannot be statically lowered.", LikelyCause: "include_tasks/include_role is templated, looped, option-bearing, or otherwise dynamic, or include_vars requires runtime scope.", Repair: "Use a simple literal include, inline the content, or keep the behavior in the trusted runtime."},
		{Code: "ansible.extra_vars_invalid", Severity: "error", Meaning: "An extra-vars input cannot participate in bounded static lowering.", LikelyCause: "The inline value or local YAML/JSON map is malformed, dynamic, non-regular, oversized, or ambiguous.", Repair: "Provide literal NAME=VALUE input or a bounded regular YAML/JSON map and resolve duplicate names."},
		{Code: "ansible.handler_unnotified", Severity: "info", Meaning: "A declared handler is never notified.", LikelyCause: "No task notifies the handler.", Repair: "Remove the handler or add the missing notify."},
		{Code: "ansible.hosts_runtime_owned", Severity: "info", Meaning: "A play targets non-local hosts while inventory connection behavior remains runtime-owned.", LikelyCause: "Static inventory may select host facts, but SSH and connection settings are not conversion semantics.", Repair: "Review the bounded host selection and provide approved connection context only in the trusted runtime."},
		{Code: "ansible.inventory_invalid", Severity: "error", Meaning: "A supplied inventory file cannot be read as bounded static inventory.", LikelyCause: "The file is malformed, unsupported, non-regular, oversized, cyclic, or exceeds host/group limits.", Repair: "Provide a bounded regular INI/YAML/JSON inventory with literal hosts, groups, and variables."},
		{Code: "ansible.inventory_pattern", Severity: "error", Meaning: "A play host target cannot be selected exactly from static inventory.", LikelyCause: "The target is missing, empty, ambiguous, templated, or uses a dynamic pattern operator.", Repair: "Use all, one exact host, or one exact group, or restructure targeting before conversion."},
		{Code: "ansible.jinja_unsupported", Severity: "error", Meaning: "A Jinja2 expression could not be lowered to a UWS core expression.", LikelyCause: "Filters, lookups, math, mixed interpolation, or multiple when conditions are in use.", Repair: "Simplify the expression, precompute the value as a variable, or restructure the task."},
		{Code: "ansible.module_unknown", Severity: "error", Meaning: "A task module is not declared by any supplied argspec document.", LikelyCause: "The collection argspec was not supplied or the FQCN is misspelled.", Repair: "Supply the collection argspec with --argspec or fix the module name."},
		{Code: "ansible.nolog_literal", Severity: "error", Meaning: "A sensitive (noLog) module parameter carries a literal value.", LikelyCause: "A secret was written directly into the playbook task.", Repair: "Replace the literal with a symbolic credential binding resolved by the runtime."},
		{Code: "ansible.playbook_shape", Severity: "warning", Meaning: "A playbook structure note was recorded during lowering.", LikelyCause: "Multiple plays, duplicate variables, or an unknown notify target.", Repair: "Review the lowered workflow against the original playbook structure."},
		{Code: "ansible.rescue_todo", Severity: "error", Meaning: "Block rescue tasks were not lowered.", LikelyCause: "Automatic onFailure lowering for rescue chains is not implemented yet.", Repair: "Restructure the block or attach reviewed onFailure handling before conversion."},
		{Code: "ansible.static_resolution", Severity: "error", Meaning: "Static Ansible include, role, or vars resolution failed.", LikelyCause: "A role/import/include/vars file is missing, ambiguous, templated, cyclic, or otherwise unavailable to the static converter.", Repair: "Supply the correct --project-dir, --roles-path, or --collections-path, make the reference static, or inline the content before conversion."},
		{Code: "ansible.variable_conflict", Severity: "error", Meaning: "Static variable values conflict at one documented precedence layer.", LikelyCause: "Multiple inventory groups, roles, vars files, imports, or extra-var inputs define incompatible equal-layer values.", Repair: "Resolve the equal-layer conflict or move the value to one explicit higher-precedence literal source."},
		{Code: "api_source.invalid", Severity: "error", Meaning: "An API source flag is malformed.", LikelyCause: "Missing kind, ID, or path.", Repair: "Use --api-source KIND:ID=PATH with a supported kind."},
		{Code: "api_source.load_error", Severity: "error", Meaning: "An API source document could not be loaded.", LikelyCause: "The path is missing, unreadable, or not a supported API source document.", Repair: "Fix the local source path or regenerate the source inventory."},
		{Code: "apply.approval_required", Severity: "error", Meaning: "Apply found mutations but no explicit approval.", LikelyCause: "--auto-approve or a verified approval artifact was not supplied.", Repair: "Review the plan and rerun apply with explicit approval."},
		{Code: "apply.baseline_drift", Severity: "error", Meaning: "Apply read-before-write found remote drift from the approved state baseline.", LikelyCause: "The remote object changed after the reviewed plan or current Ramen state is stale.", Repair: "Run refresh, review the new plan, and approve the updated baseline before applying."},
		{Code: "apply.baseline_exists", Severity: "error", Meaning: "Apply read-before-write found an existing remote object for a planned create.", LikelyCause: "The object already exists remotely or local state does not track it.", Repair: "Import or refresh the object, rename the desired resource, or review the create plan again."},
		{Code: "apply.baseline_failed", Severity: "error", Meaning: "Apply could not complete the read-before-write baseline check.", LikelyCause: "The trusted executor could not read the remote object before mutation.", Repair: "Inspect executor feedback and retry after correcting read access or mapping metadata."},
		{Code: "apply.baseline_missing", Severity: "error", Meaning: "Apply read-before-write could not find a remote object for a planned update.", LikelyCause: "The object was deleted remotely or local state is stale.", Repair: "Run refresh, review the new plan, and approve the corrected action."},
		{Code: "apply.convergence_failed", Severity: "error", Meaning: "Apply could not complete the read-after-write convergence check.", LikelyCause: "The trusted executor could not read the object after mutation.", Repair: "Inspect executor feedback and remote state before retrying."},
		{Code: "apply.convergence_missing", Severity: "error", Meaning: "Apply read-after-write reported the object missing after mutation.", LikelyCause: "The mutation did not create/update the expected object or the read identity is wrong.", Repair: "Inspect executor output, mapping metadata, and remote state before retrying."},
		{Code: "apply.document_invalid", Severity: "error", Meaning: "Ramen could not build a valid executor document for an apply action.", LikelyCause: "The mapping metadata, operation, source path, or request binding is incomplete.", Repair: "Fix the mapping/project metadata and rebuild the plan."},
		{Code: "apply.executor_failed", Severity: "error", Meaning: "The trusted executor returned an execution error.", LikelyCause: "The executor could not complete the requested API operation.", Repair: "Inspect executor feedback and retry after correcting the underlying failure."},
		{Code: "apply.executor_required", Severity: "error", Meaning: "Apply requires an explicit trusted executor.", LikelyCause: "No mock or trusted executor adapter was selected.", Repair: "Use --mock for public mock execution or configure an approved trusted executor adapter."},
		{Code: "apply.executor_unsuccessful", Severity: "error", Meaning: "The trusted executor completed but reported an unsuccessful mutation.", LikelyCause: "The API operation failed or did not converge according to executor evidence.", Repair: "Inspect executor output and mapping metadata before retrying."},
		{Code: "apply.executor_unsupported", Severity: "error", Meaning: "The selected executor does not satisfy the action requirements.", LikelyCause: "Required protocol, auth, output, idempotency, retry, or waiter capabilities are missing.", Repair: "Select an executor with the required capabilities or reduce the requested action."},
		{Code: "apply.settle_failed", Severity: "error", Meaning: "Apply could not complete the configured pre-mutation settle barrier.", LikelyCause: "A read during the settle window failed, reported the object missing, or the run was canceled.", Repair: "Inspect executor feedback, wait for the remote API lock or consistency window to clear, and retry the approved plan if still valid."},
		{Code: "destroy.operation_missing", Severity: "error", Meaning: "Destroy has no safe operation role for a resource.", LikelyCause: "The resource lacks delete, detach, disable, suspend, or remove-config operation metadata.", Repair: "Add an explicit destroy operation role or keep the resource out of destroy scope."},
		{Code: "graph.dependency_cycle", Severity: "error", Meaning: "The native resource graph contains a cycle.", LikelyCause: "Two or more resources depend on each other.", Repair: "Break the dependency cycle in the native project metadata."},
		{Code: "import.identity_invalid", Severity: "error", Meaning: "Import identity input is not a JSON object.", LikelyCause: "The --identity value is malformed or null.", Repair: "Provide a JSON object with the declared identity fields."},
		{Code: "import.identity_missing", Severity: "error", Meaning: "Required import identity metadata is missing.", LikelyCause: "The native project declares a required identity field that was not supplied.", Repair: "Provide the missing identity key or adjust the resource identity metadata."},
		{Code: "import.identity_schema_missing", Severity: "error", Meaning: "A native project resource has no importable identity metadata.", LikelyCause: "The resource lacks identity attributes, schema identity paths, and response-derived identity bindings.", Repair: "Declare structured identity metadata before importing the resource."},
		{Code: "import.identity_unknown", Severity: "error", Meaning: "Import identity input includes an undeclared key.", LikelyCause: "The supplied identity field is not present in the native resource identity schema.", Repair: "Use only declared identity keys or add the missing identity metadata."},
		{Code: "import.operation_missing", Severity: "error", Meaning: "A native project resource cannot be verified for import.", LikelyCause: "The resource lacks an import or read operation role.", Repair: "Add an import/read operation role or defer import verification for this resource."},
		{Code: "import.read_document_invalid", Severity: "error", Meaning: "Ramen could not build an import read-verification document.", LikelyCause: "The read operation mapping, source path, or identity binding metadata is incomplete.", Repair: "Fix the native project read metadata before verifying import reads."},
		{Code: "import.read_failed", Severity: "error", Meaning: "Import read verification failed.", LikelyCause: "The trusted executor could not read the remote object during import verification.", Repair: "Inspect executor feedback, identity input, and read metadata before retrying."},
		{Code: "import.read_mismatch", Severity: "error", Meaning: "Import read verification returned identity that does not match the supplied identity.", LikelyCause: "The supplied identity points at a different remote object or response binding metadata is wrong.", Repair: "Correct the identity input or mapping metadata before importing."},
		{Code: "import.read_missing", Severity: "error", Meaning: "Import read verification reported the remote object missing.", LikelyCause: "The supplied identity does not identify an existing object or the read operation is scoped incorrectly.", Repair: "Correct the identity input or create the object before importing."},
		{Code: "import.read_unsupported", Severity: "error", Meaning: "The selected executor cannot perform import read verification.", LikelyCause: "The executor lacks the protocol or output capabilities required by the read action.", Repair: "Select an executor with read/output/missing-evidence support or import without read verification."},
		{Code: "mapping.operation_unavailable", Severity: "error", Meaning: "No API operation matched the resource role.", LikelyCause: "The API source lacks the operation or the mapping metadata is incomplete.", Repair: "Add or correct the operation role in the native project."},
		{Code: "approval.identity_invalid", Severity: "error", Meaning: "Approval identity metadata is invalid.", LikelyCause: "The approver identity or deterministic approved_at timestamp is missing.", Repair: "Provide --approved-by and --approved-at in RFC3339 format when adding approval metadata."},
		{Code: "plan.prevent_destroy", Severity: "error", Meaning: "A planned delete or replace violates prevent_destroy.", LikelyCause: "The resource lifecycle blocks destructive action.", Repair: "Remove the destructive control or intentionally change lifecycle metadata."},
		{Code: "policy.deny", Severity: "error", Meaning: "A plan-time policy denied a resource action.", LikelyCause: "A Ramen policy file denies the action or resource under review.", Repair: "Change the desired state, select a different policy, or route through the required governance process."},
		{Code: "policy.file_load_error", Severity: "error", Meaning: "A policy file could not be read.", LikelyCause: "The policy path is missing or unreadable.", Repair: "Fix the --policy-file path or permissions."},
		{Code: "policy.file_parse_error", Severity: "error", Meaning: "A policy file could not be parsed.", LikelyCause: "The policy file is not valid JSON or YAML.", Repair: "Fix the policy document syntax."},
		{Code: "policy.max_deletes", Severity: "error", Meaning: "A plan exceeds the policy delete/replacement limit.", LikelyCause: "The plan contains more destructive actions than the policy allows.", Repair: "Reduce the plan scope or update the policy through the governance process."},
		{Code: "policy.version_invalid", Severity: "error", Meaning: "A policy file declares an unsupported version.", LikelyCause: "The policy was written for a different Ramen policy contract.", Repair: "Use ramen.policy.v1 or update the Ramen binary and policy file together."},
		{Code: "policy.warn", Severity: "warning", Meaning: "A plan-time policy warning matched a resource action.", LikelyCause: "The action is allowed but requires operator attention.", Repair: "Review the warning before approving or executing the plan."},
		{Code: "project.operation_missing", Severity: "error", Meaning: "A required native project operation role is absent.", LikelyCause: "The resource lacks create, read, update, delete, or import metadata for the requested action.", Repair: "Add the missing operation role with source and operation IDs."},
		{Code: "run.approval_mismatch", Severity: "error", Meaning: "An imperative run approval digest does not match current inputs.", LikelyCause: "The UWS document, target set, workspace, or state path changed after review.", Repair: "Rerun ramen run --check and approve the new digest."},
		{Code: "run.document_invalid", Severity: "error", Meaning: "The imperative UWS document failed validation.", LikelyCause: "The UWS file is malformed or violates UWS schema rules.", Repair: "Fix the UWS document and run check mode again."},
		{Code: "run.executor_required", Severity: "error", Meaning: "Imperative execution requires a trusted executor.", LikelyCause: "No executor adapter was selected for a non-check run.", Repair: "Use --mock for public mock execution or configure an approved trusted executor adapter."},
		{Code: "state.open_error", Severity: "error", Meaning: "Ramen could not open local SQLite state.", LikelyCause: "The state path is missing, corrupt, locked, or newer than the binary supports.", Repair: "Run ramen init, inspect locks, restore a backup, or upgrade the binary."},
		{Code: "validate.dependency_cycle", Severity: "error", Meaning: "Validation found a resource dependency cycle.", LikelyCause: "The project graph is cyclic.", Repair: "Adjust dependencies so the graph is acyclic."},
		{Code: "validate.attribute_required", Severity: "error", Meaning: "A required mapped attribute is missing.", LikelyCause: "Mapping schema, identity metadata, or request binding metadata declares a required path that is absent from the resource.", Repair: "Add the required desired-state attribute or adjust the mapping metadata."},
		{Code: "validate.attribute_unknown", Severity: "error", Meaning: "A resource declares an attribute outside its mapping schema.", LikelyCause: "The desired state includes a path that Ramen does not know how to validate, plan, or bind for this mapped type.", Repair: "Remove the attribute or add explicit mapping schema and binding metadata for it."},
		{Code: "validate.binding_invalid", Severity: "error", Meaning: "A request or response binding is incomplete.", LikelyCause: "The binding is missing its operation role, desired/state path, request path, or response path.", Repair: "Complete the mapping binding metadata before validating or planning the resource."},
		{Code: "validate.project_load_error", Severity: "error", Meaning: "The native project could not be loaded.", LikelyCause: "The project file is missing, invalid UWS, or has invalid Ramen metadata.", Repair: "Fix the project path and validate the UWS/Ramen profile."},
		{Code: "validate.enum_invalid", Severity: "error", Meaning: "A mapped attribute has a value outside the declared enum set.", LikelyCause: "The desired value is unsupported by the API source or mapping metadata.", Repair: "Use one of the declared enum values or update the mapping metadata if the API has changed."},
		{Code: "validate.operation_role_missing", Severity: "error", Meaning: "A resource is missing an operation role required by mapping metadata.", LikelyCause: "The resource declares required operations or mapping lifecycle roles that are absent from its operations map.", Repair: "Add the missing operation role with source and operation IDs, or remove the unsupported lifecycle requirement."},
		{Code: "validate.schema_duplicate", Severity: "error", Meaning: "A mapped resource declares the same schema path more than once.", LikelyCause: "Mapping metadata was generated or edited with duplicate path entries.", Repair: "Keep one schema entry per path."},
		{Code: "validate.schema_invalid", Severity: "error", Meaning: "A mapped resource schema entry is malformed.", LikelyCause: "A schema path is empty or otherwise unusable.", Repair: "Provide a non-empty schema path."},
		{Code: "validate.sensitive_path_unredacted", Severity: "error", Meaning: "A sensitive mapped path is not covered by redaction metadata.", LikelyCause: "Schema or response binding metadata marks a path sensitive, but resource/profile redaction omits it.", Repair: "Add the path to resource or profile redaction metadata before persisting artifacts."},
		{Code: "validate.settle_invalid", Severity: "error", Meaning: "A native resource has an unsupported settle runtime hint.", LikelyCause: "The settle hint uses an unsupported phase, predicate, or non-positive duration/interval.", Repair: "Use a positive pre-delete settle hint with read_expect exists, or remove the hint."},
		{Code: "validate.settle_read_role_missing", Severity: "error", Meaning: "A settle runtime hint requires read operation metadata.", LikelyCause: "Ramen cannot run the read-backed settle barrier because the resource has no read role.", Repair: "Add read operation metadata or remove the settle hint."},
		{Code: "validate.type_invalid", Severity: "error", Meaning: "A mapped attribute does not match the declared scalar or collection type.", LikelyCause: "The desired value type differs from the API-source or mapping metadata type.", Repair: "Correct the desired value type or update the mapping schema if the API contract changed."},
	}
	slices.SortFunc(entries, func(a, b Entry) int {
		if a.Code < b.Code {
			return -1
		}
		if a.Code > b.Code {
			return 1
		}
		return 0
	})
	return Catalog{Version: CatalogVersion, Entries: entries}
}
